# EDA - Mall Customer

In [133]:
import numpy as np

### Load Data Using Numpy genfromtxt

In [134]:
data = np.genfromtxt('Mall_Customers.csv', dtype=['i8','U6','i8','i8','i8'], names=['id', 'Gender', 'Age', 'AnnualIncome','Spending'], delimiter=',', skip_header=1)
data

array([(  1, 'Male', 19,  15, 39), (  2, 'Male', 21,  15, 81),
       (  3, 'Female', 20,  16,  6), (  4, 'Female', 23,  16, 77),
       (  5, 'Female', 31,  17, 40), (  6, 'Female', 22,  17, 76),
       (  7, 'Female', 35,  18,  6), (  8, 'Female', 23,  18, 94),
       (  9, 'Male', 64,  19,  3), ( 10, 'Female', 30,  19, 72),
       ( 11, 'Male', 67,  19, 14), ( 12, 'Female', 35,  19, 99),
       ( 13, 'Female', 58,  20, 15), ( 14, 'Female', 24,  20, 77),
       ( 15, 'Male', 37,  20, 13), ( 16, 'Male', 22,  20, 79),
       ( 17, 'Female', 35,  21, 35), ( 18, 'Male', 20,  21, 66),
       ( 19, 'Male', 52,  23, 29), ( 20, 'Female', 35,  23, 98),
       ( 21, 'Male', 35,  24, 35), ( 22, 'Male', 25,  24, 73),
       ( 23, 'Female', 46,  25,  5), ( 24, 'Male', 31,  25, 73),
       ( 25, 'Female', 54,  28, 14), ( 26, 'Male', 29,  28, 82),
       ( 27, 'Female', 45,  28, 32), ( 28, 'Male', 35,  28, 61),
       ( 29, 'Female', 40,  29, 31), ( 30, 'Female', 23,  29, 87),
       ( 31, 'Male', 60,  30,  4), ( 32, 'Female', 21,  30, 73),
       ( 33, 'Male', 53,  33,  4), ( 34, 'Male', 18,  33, 92),
       ( 35, 'Female', 49,  33, 14), ( 36, 'Female', 21,  33, 81),
       ( 37, 'Female', 42,  34, 17), ( 38, 'Female', 30,  34, 73),
       ( 39, 'Female', 36,  37, 26), ( 40, 'Female', 20,  37, 75),
       ( 41, 'Female', 65,  38, 35), ( 42, 'Male', 24,  38, 92),
       ( 43, 'Male', 48,  39, 36), ( 44, 'Female', 31,  39, 61),
       ( 45, 'Female', 49,  39, 28), ( 46, 'Female', 24,  39, 65),
       ( 47, 'Female', 50,  40, 55), ( 48, 'Female', 27,  40, 47),
       ( 49, 'Female', 29,  40, 42), ( 50, 'Female', 31,  40, 42),
       ( 51, 'Female', 49,  42, 52), ( 52, 'Male', 33,  42, 60),
       ( 53, 'Female', 31,  43, 54), ( 54, 'Male', 59,  43, 60),
       ( 55, 'Female', 50,  43, 45), ( 56, 'Male', 47,  43, 41),
       ( 57, 'Female', 51,  44, 50), ( 58, 'Male', 69,  44, 46),
       ( 59, 'Female', 27,  46, 51), ( 60, 'Male', 53,  46, 46),
       ( 61, 'Male', 70,  46, 56), ( 62, 'Male', 19,  46, 55),
       ( 63, 'Female', 67,  47, 52), ( 64, 'Female', 54,  47, 59),
       ( 65, 'Male', 63,  48, 51), ( 66, 'Male', 18,  48, 59),
       ( 67, 'Female', 43,  48, 50), ( 68, 'Female', 68,  48, 48),
       ( 69, 'Male', 19,  48, 59), ( 70, 'Female', 32,  48, 47),
       ( 71, 'Male', 70,  49, 55), ( 72, 'Female', 47,  49, 42),
       ( 73, 'Female', 60,  50, 49), ( 74, 'Female', 60,  50, 56),
       ( 75, 'Male', 59,  54, 47), ( 76, 'Male', 26,  54, 54),
       ( 77, 'Female', 45,  54, 53), ( 78, 'Male', 40,  54, 48),
       ( 79, 'Female', 23,  54, 52), ( 80, 'Female', 49,  54, 42),
       ( 81, 'Male', 57,  54, 51), ( 82, 'Male', 38,  54, 55),
       ( 83, 'Male', 67,  54, 41), ( 84, 'Female', 46,  54, 44),
       ( 85, 'Female', 21,  54, 57), ( 86, 'Male', 48,  54, 46),
       ( 87, 'Female', 55,  57, 58), ( 88, 'Female', 22,  57, 55),
       ( 89, 'Female', 34,  58, 60), ( 90, 'Female', 50,  58, 46),
       ( 91, 'Female', 68,  59, 55), ( 92, 'Male', 18,  59, 41),
       ( 93, 'Male', 48,  60, 49), ( 94, 'Female', 40,  60, 40),
       ( 95, 'Female', 32,  60, 42), ( 96, 'Male', 24,  60, 52),
       ( 97, 'Female', 47,  60, 47), ( 98, 'Female', 27,  60, 50),
       ( 99, 'Male', 48,  61, 42), (100, 'Male', 20,  61, 49),
       (101, 'Female', 23,  62, 41), (102, 'Female', 49,  62, 48),
       (103, 'Male', 67,  62, 59), (104, 'Male', 26,  62, 55),
       (105, 'Male', 49,  62, 56), (106, 'Female', 21,  62, 42),
       (107, 'Female', 66,  63, 50), (108, 'Male', 54,  63, 46),
       (109, 'Male', 68,  63, 43), (110, 'Male', 66,  63, 48),
       (111, 'Male', 65,  63, 52), (112, 'Female', 19,  63, 54),
       (113, 'Female', 38,  64, 42), (114, 'Male', 19,  64, 46),
       (115, 'Female', 18,  65, 48), (116, 'Female', 19,  65, 50),
       (117, 'Female', 63,  65, 43), (118, 'Female', 49,  65, 59),
       (119, 'Female', 51,  67, 43), (120, 'Female', 50,  67, 57),
       (121, 'Male', 27,  67, 56), (122, 'Female', 38,  67, 40),
       (123, 'Female', 40,  69, 58), (124, 'Male', 39,  69, 91),
       (125, 'Female', 23,  70, 29), (126, 'Female', 31,  70, 77),
       (127, 'Male', 43,  71, 35), (128, 'Male', 40,  71, 95),
       (129, 'Male', 59,  71, 11), (130, 'Male', 38,  71, 75),
       (131, 'Male', 47,  71,  9), (132, 'Male', 39,  71, 75),
       (133, 'Female', 25,  72, 34), (134, 'Female', 31,  72, 71),
       (135, 'Male', 20,  73,  5), (136, 'Female', 29,  73, 88),
       (137, 'Female', 44,  73,  7), (138, 'Male', 32,  73, 73),
       (139, 'Male', 19,  74, 10), (140, 'Female', 35,  74, 72),
       (141, 'Female', 57,  75,  5), (142, 'Male', 32,  75, 93),
       (143, 'Female', 28,  76, 40), (144, 'Female', 32,  76, 87),
       (145, 'Male', 25,  77, 12), (146, 'Male', 28,  77, 97),
       (147, 'Male', 48,  77, 36), (148, 'Female', 32,  77, 74),
       (149, 'Female', 34,  78, 22), (150, 'Male', 34,  78, 90),
       (151, 'Male', 43,  78, 17), (152, 'Male', 39,  78, 88),
       (153, 'Female', 44,  78, 20), (154, 'Female', 38,  78, 76),
       (155, 'Female', 47,  78, 16), (156, 'Female', 27,  78, 89),
       (157, 'Male', 37,  78,  1), (158, 'Female', 30,  78, 78),
       (159, 'Male', 34,  78,  1), (160, 'Female', 30,  78, 73),
       (161, 'Female', 56,  79, 35), (162, 'Female', 29,  79, 83),
       (163, 'Male', 19,  81,  5), (164, 'Female', 31,  81, 93),
       (165, 'Male', 50,  85, 26), (166, 'Female', 36,  85, 75),
       (167, 'Male', 42,  86, 20), (168, 'Female', 33,  86, 95),
       (169, 'Female', 36,  87, 27), (170, 'Male', 32,  87, 63),
       (171, 'Male', 40,  87, 13), (172, 'Male', 28,  87, 75),
       (173, 'Male', 36,  87, 10), (174, 'Male', 36,  87, 92),
       (175, 'Female', 52,  88, 13), (176, 'Female', 30,  88, 86),
       (177, 'Male', 58,  88, 15), (178, 'Male', 27,  88, 69),
       (179, 'Male', 59,  93, 14), (180, 'Male', 35,  93, 90),
       (181, 'Female', 37,  97, 32), (182, 'Female', 32,  97, 86),
       (183, 'Male', 46,  98, 15), (184, 'Female', 29,  98, 88),
       (185, 'Female', 41,  99, 39), (186, 'Male', 30,  99, 97),
       (187, 'Female', 54, 101, 24), (188, 'Male', 28, 101, 68),
       (189, 'Female', 41, 103, 17), (190, 'Female', 36, 103, 85),
       (191, 'Female', 34, 103, 23), (192, 'Female', 32, 103, 69),
       (193, 'Male', 33, 113,  8), (194, 'Female', 38, 113, 91),
       (195, 'Female', 47, 120, 16), (196, 'Female', 35, 120, 79),
       (197, 'Female', 45, 126, 28), (198, 'Male', 32, 126, 74),
       (199, 'Male', 32, 137, 18), (200, 'Male', 30, 137, 83)],
      dtype=[('id', '<i8'), ('Gender', '<U6'), ('Age', '<i8'), ('AnnualIncome', '<i8'), ('Spending', '<i8')])

**Note:**

- **Use U6 instead of S6**

**Reference**
- https://numpy.org/doc/stable/reference/generated/numpy.genfromtxt.html
- https://stackoverflow.com/questions/33655641/b-character-added-when-using-numpy-loadtxt

In [135]:
#Check data type of array
type(data)

numpy.ndarray

In [136]:
# Check data type of individual columns
data.dtype

dtype([('id', '<i8'), ('Gender', '<U6'), ('Age', '<i8'), ('AnnualIncome', '<i8'), ('Spending', '<i8')])

In [137]:
# Check shape of array
data.shape

(200,)

In [138]:
# Check dimension of array
data.ndim

1

In [139]:
# Extract first record
first_record = data[0]
first_record

(1, 'Male', 19, 15, 39)

In [140]:
# Check data type of first record
type(first_record)

numpy.void

It looks like tuple but it actually is numpy.void data type.

- https://stackoverflow.com/questions/25247190/how-to-use-numpy-void-type

In [141]:
# Filter gender with male
# Will use the list to double check when doing conversion
data['Gender'] == 'Male'

array([ True,  True, False, False, False, False, False, False,  True,
       False,  True, False, False, False,  True,  True, False,  True,
        True, False,  True,  True, False,  True, False,  True, False,
        True, False, False,  True, False,  True,  True, False, False,
       False, False, False, False, False,  True,  True, False, False,
       False, False, False, False, False, False,  True, False,  True,
       False,  True, False,  True, False,  True,  True,  True, False,
       False,  True,  True, False, False,  True, False,  True, False,
       False, False,  True,  True, False,  True, False, False,  True,
        True,  True, False, False,  True, False, False, False, False,
       False,  True,  True, False, False,  True, False, False,  True,
        True, False, False,  True,  True,  True, False, False,  True,
        True,  True,  True, False, False,  True, False, False, False,
       False, False, False,  True, False, False,  True, False, False,
        True,  True,  True,  True,  True,  True, False, False,  True,
       False, False,  True,  True, False, False,  True, False, False,
        True,  True,  True, False, False,  True,  True,  True, False,
       False, False, False,  True, False,  True, False, False, False,
        True, False,  True, False,  True, False, False,  True,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
       False, False,  True, False, False,  True, False,  True, False,
       False, False, False,  True, False, False, False, False,  True,
        True,  True])

**We will be converting Male to 1 and Female to 0.**

In [142]:
# Try np.where without actual assignment. Check if conversion is ok.
np.where(data['Gender'] == 'Male', 1, 0)

array([1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1])

In [143]:
# Perform actual conversion
data['Gender'] = np.where(data['Gender'] == 'Male', 1, 0)
data

array([(  1, '1', 19,  15, 39), (  2, '1', 21,  15, 81),
       (  3, '0', 20,  16,  6), (  4, '0', 23,  16, 77),
       (  5, '0', 31,  17, 40), (  6, '0', 22,  17, 76),
       (  7, '0', 35,  18,  6), (  8, '0', 23,  18, 94),
       (  9, '1', 64,  19,  3), ( 10, '0', 30,  19, 72),
       ( 11, '1', 67,  19, 14), ( 12, '0', 35,  19, 99),
       ( 13, '0', 58,  20, 15), ( 14, '0', 24,  20, 77),
       ( 15, '1', 37,  20, 13), ( 16, '1', 22,  20, 79),
       ( 17, '0', 35,  21, 35), ( 18, '1', 20,  21, 66),
       ( 19, '1', 52,  23, 29), ( 20, '0', 35,  23, 98),
       ( 21, '1', 35,  24, 35), ( 22, '1', 25,  24, 73),
       ( 23, '0', 46,  25,  5), ( 24, '1', 31,  25, 73),
       ( 25, '0', 54,  28, 14), ( 26, '1', 29,  28, 82),
       ( 27, '0', 45,  28, 32), ( 28, '1', 35,  28, 61),
       ( 29, '0', 40,  29, 31), ( 30, '0', 23,  29, 87),
       ( 31, '1', 60,  30,  4), ( 32, '0', 21,  30, 73),
       ( 33, '1', 53,  33,  4), ( 34, '1', 18,  33, 92),
       ( 35, '0', 49,  33, 14), ( 36, '0', 21,  33, 81),
       ( 37, '0', 42,  34, 17), ( 38, '0', 30,  34, 73),
       ( 39, '0', 36,  37, 26), ( 40, '0', 20,  37, 75),
       ( 41, '0', 65,  38, 35), ( 42, '1', 24,  38, 92),
       ( 43, '1', 48,  39, 36), ( 44, '0', 31,  39, 61),
       ( 45, '0', 49,  39, 28), ( 46, '0', 24,  39, 65),
       ( 47, '0', 50,  40, 55), ( 48, '0', 27,  40, 47),
       ( 49, '0', 29,  40, 42), ( 50, '0', 31,  40, 42),
       ( 51, '0', 49,  42, 52), ( 52, '1', 33,  42, 60),
       ( 53, '0', 31,  43, 54), ( 54, '1', 59,  43, 60),
       ( 55, '0', 50,  43, 45), ( 56, '1', 47,  43, 41),
       ( 57, '0', 51,  44, 50), ( 58, '1', 69,  44, 46),
       ( 59, '0', 27,  46, 51), ( 60, '1', 53,  46, 46),
       ( 61, '1', 70,  46, 56), ( 62, '1', 19,  46, 55),
       ( 63, '0', 67,  47, 52), ( 64, '0', 54,  47, 59),
       ( 65, '1', 63,  48, 51), ( 66, '1', 18,  48, 59),
       ( 67, '0', 43,  48, 50), ( 68, '0', 68,  48, 48),
       ( 69, '1', 19,  48, 59), ( 70, '0', 32,  48, 47),
       ( 71, '1', 70,  49, 55), ( 72, '0', 47,  49, 42),
       ( 73, '0', 60,  50, 49), ( 74, '0', 60,  50, 56),
       ( 75, '1', 59,  54, 47), ( 76, '1', 26,  54, 54),
       ( 77, '0', 45,  54, 53), ( 78, '1', 40,  54, 48),
       ( 79, '0', 23,  54, 52), ( 80, '0', 49,  54, 42),
       ( 81, '1', 57,  54, 51), ( 82, '1', 38,  54, 55),
       ( 83, '1', 67,  54, 41), ( 84, '0', 46,  54, 44),
       ( 85, '0', 21,  54, 57), ( 86, '1', 48,  54, 46),
       ( 87, '0', 55,  57, 58), ( 88, '0', 22,  57, 55),
       ( 89, '0', 34,  58, 60), ( 90, '0', 50,  58, 46),
       ( 91, '0', 68,  59, 55), ( 92, '1', 18,  59, 41),
       ( 93, '1', 48,  60, 49), ( 94, '0', 40,  60, 40),
       ( 95, '0', 32,  60, 42), ( 96, '1', 24,  60, 52),
       ( 97, '0', 47,  60, 47), ( 98, '0', 27,  60, 50),
       ( 99, '1', 48,  61, 42), (100, '1', 20,  61, 49),
       (101, '0', 23,  62, 41), (102, '0', 49,  62, 48),
       (103, '1', 67,  62, 59), (104, '1', 26,  62, 55),
       (105, '1', 49,  62, 56), (106, '0', 21,  62, 42),
       (107, '0', 66,  63, 50), (108, '1', 54,  63, 46),
       (109, '1', 68,  63, 43), (110, '1', 66,  63, 48),
       (111, '1', 65,  63, 52), (112, '0', 19,  63, 54),
       (113, '0', 38,  64, 42), (114, '1', 19,  64, 46),
       (115, '0', 18,  65, 48), (116, '0', 19,  65, 50),
       (117, '0', 63,  65, 43), (118, '0', 49,  65, 59),
       (119, '0', 51,  67, 43), (120, '0', 50,  67, 57),
       (121, '1', 27,  67, 56), (122, '0', 38,  67, 40),
       (123, '0', 40,  69, 58), (124, '1', 39,  69, 91),
       (125, '0', 23,  70, 29), (126, '0', 31,  70, 77),
       (127, '1', 43,  71, 35), (128, '1', 40,  71, 95),
       (129, '1', 59,  71, 11), (130, '1', 38,  71, 75),
       (131, '1', 47,  71,  9), (132, '1', 39,  71, 75),
       (133, '0', 25,  72, 34), (134, '0', 31,  72, 71),
       (135, '1', 20,  73,  5), (136, '0', 29,  73, 88),
       (137, '0', 44,  73,  7), (138, '1', 32,  73, 73),
       (139, '1', 19,  74, 10), (140, '0', 35,  74, 72),
       (141, '0', 57,  75,  5), (142, '1', 32,  75, 93),
       (143, '0', 28,  76, 40), (144, '0', 32,  76, 87),
       (145, '1', 25,  77, 12), (146, '1', 28,  77, 97),
       (147, '1', 48,  77, 36), (148, '0', 32,  77, 74),
       (149, '0', 34,  78, 22), (150, '1', 34,  78, 90),
       (151, '1', 43,  78, 17), (152, '1', 39,  78, 88),
       (153, '0', 44,  78, 20), (154, '0', 38,  78, 76),
       (155, '0', 47,  78, 16), (156, '0', 27,  78, 89),
       (157, '1', 37,  78,  1), (158, '0', 30,  78, 78),
       (159, '1', 34,  78,  1), (160, '0', 30,  78, 73),
       (161, '0', 56,  79, 35), (162, '0', 29,  79, 83),
       (163, '1', 19,  81,  5), (164, '0', 31,  81, 93),
       (165, '1', 50,  85, 26), (166, '0', 36,  85, 75),
       (167, '1', 42,  86, 20), (168, '0', 33,  86, 95),
       (169, '0', 36,  87, 27), (170, '1', 32,  87, 63),
       (171, '1', 40,  87, 13), (172, '1', 28,  87, 75),
       (173, '1', 36,  87, 10), (174, '1', 36,  87, 92),
       (175, '0', 52,  88, 13), (176, '0', 30,  88, 86),
       (177, '1', 58,  88, 15), (178, '1', 27,  88, 69),
       (179, '1', 59,  93, 14), (180, '1', 35,  93, 90),
       (181, '0', 37,  97, 32), (182, '0', 32,  97, 86),
       (183, '1', 46,  98, 15), (184, '0', 29,  98, 88),
       (185, '0', 41,  99, 39), (186, '1', 30,  99, 97),
       (187, '0', 54, 101, 24), (188, '1', 28, 101, 68),
       (189, '0', 41, 103, 17), (190, '0', 36, 103, 85),
       (191, '0', 34, 103, 23), (192, '0', 32, 103, 69),
       (193, '1', 33, 113,  8), (194, '0', 38, 113, 91),
       (195, '0', 47, 120, 16), (196, '0', 35, 120, 79),
       (197, '0', 45, 126, 28), (198, '1', 32, 126, 74),
       (199, '1', 32, 137, 18), (200, '1', 30, 137, 83)],
      dtype=[('id', '<i8'), ('Gender', '<U6'), ('Age', '<i8'), ('AnnualIncome', '<i8'), ('Spending', '<i8')])

The gender columns still remain as string.

Convert array with dtype void to numpy array.

https://stackoverflow.com/questions/53067064/convert-numpy-void-to-numpy-ndarray

In [144]:
data_list = data.tolist()
data_list

[(1, '1', 19, 15, 39),
 (2, '1', 21, 15, 81),
 (3, '0', 20, 16, 6),
 (4, '0', 23, 16, 77),
 (5, '0', 31, 17, 40),
 (6, '0', 22, 17, 76),
 (7, '0', 35, 18, 6),
 (8, '0', 23, 18, 94),
 (9, '1', 64, 19, 3),
 (10, '0', 30, 19, 72),
 (11, '1', 67, 19, 14),
 (12, '0', 35, 19, 99),
 (13, '0', 58, 20, 15),
 (14, '0', 24, 20, 77),
 (15, '1', 37, 20, 13),
 (16, '1', 22, 20, 79),
 (17, '0', 35, 21, 35),
 (18, '1', 20, 21, 66),
 (19, '1', 52, 23, 29),
 (20, '0', 35, 23, 98),
 (21, '1', 35, 24, 35),
 (22, '1', 25, 24, 73),
 (23, '0', 46, 25, 5),
 (24, '1', 31, 25, 73),
 (25, '0', 54, 28, 14),
 (26, '1', 29, 28, 82),
 (27, '0', 45, 28, 32),
 (28, '1', 35, 28, 61),
 (29, '0', 40, 29, 31),
 (30, '0', 23, 29, 87),
 (31, '1', 60, 30, 4),
 (32, '0', 21, 30, 73),
 (33, '1', 53, 33, 4),
 (34, '1', 18, 33, 92),
 (35, '0', 49, 33, 14),
 (36, '0', 21, 33, 81),
 (37, '0', 42, 34, 17),
 (38, '0', 30, 34, 73),
 (39, '0', 36, 37, 26),
 (40, '0', 20, 37, 75),
 (41, '0', 65, 38, 35),
 (42, '1', 24, 38, 92),
 (43, '1', 48, 39, 36),
 (44, '0', 31, 39, 61),
 (45, '0', 49, 39, 28),
 (46, '0', 24, 39, 65),
 (47, '0', 50, 40, 55),
 (48, '0', 27, 40, 47),
 (49, '0', 29, 40, 42),
 (50, '0', 31, 40, 42),
 (51, '0', 49, 42, 52),
 (52, '1', 33, 42, 60),
 (53, '0', 31, 43, 54),
 (54, '1', 59, 43, 60),
 (55, '0', 50, 43, 45),
 (56, '1', 47, 43, 41),
 (57, '0', 51, 44, 50),
 (58, '1', 69, 44, 46),
 (59, '0', 27, 46, 51),
 (60, '1', 53, 46, 46),
 (61, '1', 70, 46, 56),
 (62, '1', 19, 46, 55),
 (63, '0', 67, 47, 52),
 (64, '0', 54, 47, 59),
 (65, '1', 63, 48, 51),
 (66, '1', 18, 48, 59),
 (67, '0', 43, 48, 50),
 (68, '0', 68, 48, 48),
 (69, '1', 19, 48, 59),
 (70, '0', 32, 48, 47),
 (71, '1', 70, 49, 55),
 (72, '0', 47, 49, 42),
 (73, '0', 60, 50, 49),
 (74, '0', 60, 50, 56),
 (75, '1', 59, 54, 47),
 (76, '1', 26, 54, 54),
 (77, '0', 45, 54, 53),
 (78, '1', 40, 54, 48),
 (79, '0', 23, 54, 52),
 (80, '0', 49, 54, 42),
 (81, '1', 57, 54, 51),
 (82, '1', 38, 54, 55),
 (83, '1', 67, 54, 41),
 (84, '0', 46, 54, 44),
 (85, '0', 21, 54, 57),
 (86, '1', 48, 54, 46),
 (87, '0', 55, 57, 58),
 (88, '0', 22, 57, 55),
 (89, '0', 34, 58, 60),
 (90, '0', 50, 58, 46),
 (91, '0', 68, 59, 55),
 (92, '1', 18, 59, 41),
 (93, '1', 48, 60, 49),
 (94, '0', 40, 60, 40),
 (95, '0', 32, 60, 42),
 (96, '1', 24, 60, 52),
 (97, '0', 47, 60, 47),
 (98, '0', 27, 60, 50),
 (99, '1', 48, 61, 42),
 (100, '1', 20, 61, 49),
 (101, '0', 23, 62, 41),
 (102, '0', 49, 62, 48),
 (103, '1', 67, 62, 59),
 (104, '1', 26, 62, 55),
 (105, '1', 49, 62, 56),
 (106, '0', 21, 62, 42),
 (107, '0', 66, 63, 50),
 (108, '1', 54, 63, 46),
 (109, '1', 68, 63, 43),
 (110, '1', 66, 63, 48),
 (111, '1', 65, 63, 52),
 (112, '0', 19, 63, 54),
 (113, '0', 38, 64, 42),
 (114, '1', 19, 64, 46),
 (115, '0', 18, 65, 48),
 (116, '0', 19, 65, 50),
 (117, '0', 63, 65, 43),
 (118, '0', 49, 65, 59),
 (119, '0', 51, 67, 43),
 (120, '0', 50, 67, 57),
 (121, '1', 27, 67, 56),
 (122, '0', 38, 67, 40),
 (123, '0', 40, 69, 58),
 (124, '1', 39, 69, 91),
 (125, '0', 23, 70, 29),
 (126, '0', 31, 70, 77),
 (127, '1', 43, 71, 35),
 (128, '1', 40, 71, 95),
 (129, '1', 59, 71, 11),
 (130, '1', 38, 71, 75),
 (131, '1', 47, 71, 9),
 (132, '1', 39, 71, 75),
 (133, '0', 25, 72, 34),
 (134, '0', 31, 72, 71),
 (135, '1', 20, 73, 5),
 (136, '0', 29, 73, 88),
 (137, '0', 44, 73, 7),
 (138, '1', 32, 73, 73),
 (139, '1', 19, 74, 10),
 (140, '0', 35, 74, 72),
 (141, '0', 57, 75, 5),
 (142, '1', 32, 75, 93),
 (143, '0', 28, 76, 40),
 (144, '0', 32, 76, 87),
 (145, '1', 25, 77, 12),
 (146, '1', 28, 77, 97),
 (147, '1', 48, 77, 36),
 (148, '0', 32, 77, 74),
 (149, '0', 34, 78, 22),
 (150, '1', 34, 78, 90),
 (151, '1', 43, 78, 17),
 (152, '1', 39, 78, 88),
 (153, '0', 44, 78, 20),
 (154, '0', 38, 78, 76),
 (155, '0', 47, 78, 16),
 (156, '0', 27, 78, 89),
 (157, '1', 37, 78, 1),
 (158, '0', 30, 78, 78),
 (159, '1', 34, 78, 1),
 (160, '0', 30, 78, 73),
 (161, '0', 56, 79, 35),
 (162, '0', 29, 79, 83),
 (163, '1', 19, 81, 5),
 (164, '0', 31, 81, 93),
 (165, '1', 50, 85, 26),
 (166, '0', 36, 85, 75),
 (167, '1', 42, 86, 20),
 (168, '0', 33, 86, 95),
 (169, '0', 36, 87, 27),
 (170, '1', 32, 87, 63),
 (171, '1', 40, 87, 13),
 (172, '1', 28, 87, 75),
 (173, '1', 36, 87, 10),
 (174, '1', 36, 87, 92),
 (175, '0', 52, 88, 13),
 (176, '0', 30, 88, 86),
 (177, '1', 58, 88, 15),
 (178, '1', 27, 88, 69),
 (179, '1', 59, 93, 14),
 (180, '1', 35, 93, 90),
 (181, '0', 37, 97, 32),
 (182, '0', 32, 97, 86),
 (183, '1', 46, 98, 15),
 (184, '0', 29, 98, 88),
 (185, '0', 41, 99, 39),
 (186, '1', 30, 99, 97),
 (187, '0', 54, 101, 24),
 (188, '1', 28, 101, 68),
 (189, '0', 41, 103, 17),
 (190, '0', 36, 103, 85),
 (191, '0', 34, 103, 23),
 (192, '0', 32, 103, 69),
 (193, '1', 33, 113, 8),
 (194, '0', 38, 113, 91),
 (195, '0', 47, 120, 16),
 (196, '0', 35, 120, 79),
 (197, '0', 45, 126, 28),
 (198, '1', 32, 126, 74),
 (199, '1', 32, 137, 18),
 (200, '1', 30, 137, 83)]

In [145]:
type(data_list)

list

In [146]:
data_new = np.array(data_list)
data_new

array([['1', '1', '19', '15', '39'],
       ['2', '1', '21', '15', '81'],
       ['3', '0', '20', '16', '6'],
       ['4', '0', '23', '16', '77'],
       ['5', '0', '31', '17', '40'],
       ['6', '0', '22', '17', '76'],
       ['7', '0', '35', '18', '6'],
       ['8', '0', '23', '18', '94'],
       ['9', '1', '64', '19', '3'],
       ['10', '0', '30', '19', '72'],
       ['11', '1', '67', '19', '14'],
       ['12', '0', '35', '19', '99'],
       ['13', '0', '58', '20', '15'],
       ['14', '0', '24', '20', '77'],
       ['15', '1', '37', '20', '13'],
       ['16', '1', '22', '20', '79'],
       ['17', '0', '35', '21', '35'],
       ['18', '1', '20', '21', '66'],
       ['19', '1', '52', '23', '29'],
       ['20', '0', '35', '23', '98'],
       ['21', '1', '35', '24', '35'],
       ['22', '1', '25', '24', '73'],
       ['23', '0', '46', '25', '5'],
       ['24', '1', '31', '25', '73'],
       ['25', '0', '54', '28', '14'],
       ['26', '1', '29', '28', '82'],
       ['27', '0', '45', '28', '32'],
       ['28', '1', '35', '28', '61'],
       ['29', '0', '40', '29', '31'],
       ['30', '0', '23', '29', '87'],
       ['31', '1', '60', '30', '4'],
       ['32', '0', '21', '30', '73'],
       ['33', '1', '53', '33', '4'],
       ['34', '1', '18', '33', '92'],
       ['35', '0', '49', '33', '14'],
       ['36', '0', '21', '33', '81'],
       ['37', '0', '42', '34', '17'],
       ['38', '0', '30', '34', '73'],
       ['39', '0', '36', '37', '26'],
       ['40', '0', '20', '37', '75'],
       ['41', '0', '65', '38', '35'],
       ['42', '1', '24', '38', '92'],
       ['43', '1', '48', '39', '36'],
       ['44', '0', '31', '39', '61'],
       ['45', '0', '49', '39', '28'],
       ['46', '0', '24', '39', '65'],
       ['47', '0', '50', '40', '55'],
       ['48', '0', '27', '40', '47'],
       ['49', '0', '29', '40', '42'],
       ['50', '0', '31', '40', '42'],
       ['51', '0', '49', '42', '52'],
       ['52', '1', '33', '42', '60'],
       ['53', '0', '31', '43', '54'],
       ['54', '1', '59', '43', '60'],
       ['55', '0', '50', '43', '45'],
       ['56', '1', '47', '43', '41'],
       ['57', '0', '51', '44', '50'],
       ['58', '1', '69', '44', '46'],
       ['59', '0', '27', '46', '51'],
       ['60', '1', '53', '46', '46'],
       ['61', '1', '70', '46', '56'],
       ['62', '1', '19', '46', '55'],
       ['63', '0', '67', '47', '52'],
       ['64', '0', '54', '47', '59'],
       ['65', '1', '63', '48', '51'],
       ['66', '1', '18', '48', '59'],
       ['67', '0', '43', '48', '50'],
       ['68', '0', '68', '48', '48'],
       ['69', '1', '19', '48', '59'],
       ['70', '0', '32', '48', '47'],
       ['71', '1', '70', '49', '55'],
       ['72', '0', '47', '49', '42'],
       ['73', '0', '60', '50', '49'],
       ['74', '0', '60', '50', '56'],
       ['75', '1', '59', '54', '47'],
       ['76', '1', '26', '54', '54'],
       ['77', '0', '45', '54', '53'],
       ['78', '1', '40', '54', '48'],
       ['79', '0', '23', '54', '52'],
       ['80', '0', '49', '54', '42'],
       ['81', '1', '57', '54', '51'],
       ['82', '1', '38', '54', '55'],
       ['83', '1', '67', '54', '41'],
       ['84', '0', '46', '54', '44'],
       ['85', '0', '21', '54', '57'],
       ['86', '1', '48', '54', '46'],
       ['87', '0', '55', '57', '58'],
       ['88', '0', '22', '57', '55'],
       ['89', '0', '34', '58', '60'],
       ['90', '0', '50', '58', '46'],
       ['91', '0', '68', '59', '55'],
       ['92', '1', '18', '59', '41'],
       ['93', '1', '48', '60', '49'],
       ['94', '0', '40', '60', '40'],
       ['95', '0', '32', '60', '42'],
       ['96', '1', '24', '60', '52'],
       ['97', '0', '47', '60', '47'],
       ['98', '0', '27', '60', '50'],
       ['99', '1', '48', '61', '42'],
       ['100', '1', '20', '61', '49'],
       ['101', '0', '23', '62', '41'],
       ['102', '0', '49', '62', '48'],
       ['103', '1', '67', '62', '59'],
       ['104', '1', '26', '62', '55'],
       ['105', '1', '49', '62', '56'],
       ['106', '0', '21', '62', '42'],
       ['107', '0', '66', '63', '50'],
       ['108', '1', '54', '63', '46'],
       ['109', '1', '68', '63', '43'],
       ['110', '1', '66', '63', '48'],
       ['111', '1', '65', '63', '52'],
       ['112', '0', '19', '63', '54'],
       ['113', '0', '38', '64', '42'],
       ['114', '1', '19', '64', '46'],
       ['115', '0', '18', '65', '48'],
       ['116', '0', '19', '65', '50'],
       ['117', '0', '63', '65', '43'],
       ['118', '0', '49', '65', '59'],
       ['119', '0', '51', '67', '43'],
       ['120', '0', '50', '67', '57'],
       ['121', '1', '27', '67', '56'],
       ['122', '0', '38', '67', '40'],
       ['123', '0', '40', '69', '58'],
       ['124', '1', '39', '69', '91'],
       ['125', '0', '23', '70', '29'],
       ['126', '0', '31', '70', '77'],
       ['127', '1', '43', '71', '35'],
       ['128', '1', '40', '71', '95'],
       ['129', '1', '59', '71', '11'],
       ['130', '1', '38', '71', '75'],
       ['131', '1', '47', '71', '9'],
       ['132', '1', '39', '71', '75'],
       ['133', '0', '25', '72', '34'],
       ['134', '0', '31', '72', '71'],
       ['135', '1', '20', '73', '5'],
       ['136', '0', '29', '73', '88'],
       ['137', '0', '44', '73', '7'],
       ['138', '1', '32', '73', '73'],
       ['139', '1', '19', '74', '10'],
       ['140', '0', '35', '74', '72'],
       ['141', '0', '57', '75', '5'],
       ['142', '1', '32', '75', '93'],
       ['143', '0', '28', '76', '40'],
       ['144', '0', '32', '76', '87'],
       ['145', '1', '25', '77', '12'],
       ['146', '1', '28', '77', '97'],
       ['147', '1', '48', '77', '36'],
       ['148', '0', '32', '77', '74'],
       ['149', '0', '34', '78', '22'],
       ['150', '1', '34', '78', '90'],
       ['151', '1', '43', '78', '17'],
       ['152', '1', '39', '78', '88'],
       ['153', '0', '44', '78', '20'],
       ['154', '0', '38', '78', '76'],
       ['155', '0', '47', '78', '16'],
       ['156', '0', '27', '78', '89'],
       ['157', '1', '37', '78', '1'],
       ['158', '0', '30', '78', '78'],
       ['159', '1', '34', '78', '1'],
       ['160', '0', '30', '78', '73'],
       ['161', '0', '56', '79', '35'],
       ['162', '0', '29', '79', '83'],
       ['163', '1', '19', '81', '5'],
       ['164', '0', '31', '81', '93'],
       ['165', '1', '50', '85', '26'],
       ['166', '0', '36', '85', '75'],
       ['167', '1', '42', '86', '20'],
       ['168', '0', '33', '86', '95'],
       ['169', '0', '36', '87', '27'],
       ['170', '1', '32', '87', '63'],
       ['171', '1', '40', '87', '13'],
       ['172', '1', '28', '87', '75'],
       ['173', '1', '36', '87', '10'],
       ['174', '1', '36', '87', '92'],
       ['175', '0', '52', '88', '13'],
       ['176', '0', '30', '88', '86'],
       ['177', '1', '58', '88', '15'],
       ['178', '1', '27', '88', '69'],
       ['179', '1', '59', '93', '14'],
       ['180', '1', '35', '93', '90'],
       ['181', '0', '37', '97', '32'],
       ['182', '0', '32', '97', '86'],
       ['183', '1', '46', '98', '15'],
       ['184', '0', '29', '98', '88'],
       ['185', '0', '41', '99', '39'],
       ['186', '1', '30', '99', '97'],
       ['187', '0', '54', '101', '24'],
       ['188', '1', '28', '101', '68'],
       ['189', '0', '41', '103', '17'],
       ['190', '0', '36', '103', '85'],
       ['191', '0', '34', '103', '23'],
       ['192', '0', '32', '103', '69'],
       ['193', '1', '33', '113', '8'],
       ['194', '0', '38', '113', '91'],
       ['195', '0', '47', '120', '16'],
       ['196', '0', '35', '120', '79'],
       ['197', '0', '45', '126', '28'],
       ['198', '1', '32', '126', '74'],
       ['199', '1', '32', '137', '18'],
       ['200', '1', '30', '137', '83']], dtype='<U21')

All dtype is string. Will convert all to int.

In [147]:
data_new = data_new.astype(int)
data_new

array([[  1,   1,  19,  15,  39],
       [  2,   1,  21,  15,  81],
       [  3,   0,  20,  16,   6],
       [  4,   0,  23,  16,  77],
       [  5,   0,  31,  17,  40],
       [  6,   0,  22,  17,  76],
       [  7,   0,  35,  18,   6],
       [  8,   0,  23,  18,  94],
       [  9,   1,  64,  19,   3],
       [ 10,   0,  30,  19,  72],
       [ 11,   1,  67,  19,  14],
       [ 12,   0,  35,  19,  99],
       [ 13,   0,  58,  20,  15],
       [ 14,   0,  24,  20,  77],
       [ 15,   1,  37,  20,  13],
       [ 16,   1,  22,  20,  79],
       [ 17,   0,  35,  21,  35],
       [ 18,   1,  20,  21,  66],
       [ 19,   1,  52,  23,  29],
       [ 20,   0,  35,  23,  98],
       [ 21,   1,  35,  24,  35],
       [ 22,   1,  25,  24,  73],
       [ 23,   0,  46,  25,   5],
       [ 24,   1,  31,  25,  73],
       [ 25,   0,  54,  28,  14],
       [ 26,   1,  29,  28,  82],
       [ 27,   0,  45,  28,  32],
       [ 28,   1,  35,  28,  61],
       [ 29,   0,  40,  29,  31],
       [ 30,   0,  23,  29,  87],
       [ 31,   1,  60,  30,   4],
       [ 32,   0,  21,  30,  73],
       [ 33,   1,  53,  33,   4],
       [ 34,   1,  18,  33,  92],
       [ 35,   0,  49,  33,  14],
       [ 36,   0,  21,  33,  81],
       [ 37,   0,  42,  34,  17],
       [ 38,   0,  30,  34,  73],
       [ 39,   0,  36,  37,  26],
       [ 40,   0,  20,  37,  75],
       [ 41,   0,  65,  38,  35],
       [ 42,   1,  24,  38,  92],
       [ 43,   1,  48,  39,  36],
       [ 44,   0,  31,  39,  61],
       [ 45,   0,  49,  39,  28],
       [ 46,   0,  24,  39,  65],
       [ 47,   0,  50,  40,  55],
       [ 48,   0,  27,  40,  47],
       [ 49,   0,  29,  40,  42],
       [ 50,   0,  31,  40,  42],
       [ 51,   0,  49,  42,  52],
       [ 52,   1,  33,  42,  60],
       [ 53,   0,  31,  43,  54],
       [ 54,   1,  59,  43,  60],
       [ 55,   0,  50,  43,  45],
       [ 56,   1,  47,  43,  41],
       [ 57,   0,  51,  44,  50],
       [ 58,   1,  69,  44,  46],
       [ 59,   0,  27,  46,  51],
       [ 60,   1,  53,  46,  46],
       [ 61,   1,  70,  46,  56],
       [ 62,   1,  19,  46,  55],
       [ 63,   0,  67,  47,  52],
       [ 64,   0,  54,  47,  59],
       [ 65,   1,  63,  48,  51],
       [ 66,   1,  18,  48,  59],
       [ 67,   0,  43,  48,  50],
       [ 68,   0,  68,  48,  48],
       [ 69,   1,  19,  48,  59],
       [ 70,   0,  32,  48,  47],
       [ 71,   1,  70,  49,  55],
       [ 72,   0,  47,  49,  42],
       [ 73,   0,  60,  50,  49],
       [ 74,   0,  60,  50,  56],
       [ 75,   1,  59,  54,  47],
       [ 76,   1,  26,  54,  54],
       [ 77,   0,  45,  54,  53],
       [ 78,   1,  40,  54,  48],
       [ 79,   0,  23,  54,  52],
       [ 80,   0,  49,  54,  42],
       [ 81,   1,  57,  54,  51],
       [ 82,   1,  38,  54,  55],
       [ 83,   1,  67,  54,  41],
       [ 84,   0,  46,  54,  44],
       [ 85,   0,  21,  54,  57],
       [ 86,   1,  48,  54,  46],
       [ 87,   0,  55,  57,  58],
       [ 88,   0,  22,  57,  55],
       [ 89,   0,  34,  58,  60],
       [ 90,   0,  50,  58,  46],
       [ 91,   0,  68,  59,  55],
       [ 92,   1,  18,  59,  41],
       [ 93,   1,  48,  60,  49],
       [ 94,   0,  40,  60,  40],
       [ 95,   0,  32,  60,  42],
       [ 96,   1,  24,  60,  52],
       [ 97,   0,  47,  60,  47],
       [ 98,   0,  27,  60,  50],
       [ 99,   1,  48,  61,  42],
       [100,   1,  20,  61,  49],
       [101,   0,  23,  62,  41],
       [102,   0,  49,  62,  48],
       [103,   1,  67,  62,  59],
       [104,   1,  26,  62,  55],
       [105,   1,  49,  62,  56],
       [106,   0,  21,  62,  42],
       [107,   0,  66,  63,  50],
       [108,   1,  54,  63,  46],
       [109,   1,  68,  63,  43],
       [110,   1,  66,  63,  48],
       [111,   1,  65,  63,  52],
       [112,   0,  19,  63,  54],
       [113,   0,  38,  64,  42],
       [114,   1,  19,  64,  46],
       [115,   0,  18,  65,  48],
       [116,   0,  19,  65,  50],
       [117,   0,  63,  65,  43],
       [118,   0,  49,  65,  59],
       [119,   0,  51,  67,  43],
       [120,   0,  50,  67,  57],
       [121,   1,  27,  67,  56],
       [122,   0,  38,  67,  40],
       [123,   0,  40,  69,  58],
       [124,   1,  39,  69,  91],
       [125,   0,  23,  70,  29],
       [126,   0,  31,  70,  77],
       [127,   1,  43,  71,  35],
       [128,   1,  40,  71,  95],
       [129,   1,  59,  71,  11],
       [130,   1,  38,  71,  75],
       [131,   1,  47,  71,   9],
       [132,   1,  39,  71,  75],
       [133,   0,  25,  72,  34],
       [134,   0,  31,  72,  71],
       [135,   1,  20,  73,   5],
       [136,   0,  29,  73,  88],
       [137,   0,  44,  73,   7],
       [138,   1,  32,  73,  73],
       [139,   1,  19,  74,  10],
       [140,   0,  35,  74,  72],
       [141,   0,  57,  75,   5],
       [142,   1,  32,  75,  93],
       [143,   0,  28,  76,  40],
       [144,   0,  32,  76,  87],
       [145,   1,  25,  77,  12],
       [146,   1,  28,  77,  97],
       [147,   1,  48,  77,  36],
       [148,   0,  32,  77,  74],
       [149,   0,  34,  78,  22],
       [150,   1,  34,  78,  90],
       [151,   1,  43,  78,  17],
       [152,   1,  39,  78,  88],
       [153,   0,  44,  78,  20],
       [154,   0,  38,  78,  76],
       [155,   0,  47,  78,  16],
       [156,   0,  27,  78,  89],
       [157,   1,  37,  78,   1],
       [158,   0,  30,  78,  78],
       [159,   1,  34,  78,   1],
       [160,   0,  30,  78,  73],
       [161,   0,  56,  79,  35],
       [162,   0,  29,  79,  83],
       [163,   1,  19,  81,   5],
       [164,   0,  31,  81,  93],
       [165,   1,  50,  85,  26],
       [166,   0,  36,  85,  75],
       [167,   1,  42,  86,  20],
       [168,   0,  33,  86,  95],
       [169,   0,  36,  87,  27],
       [170,   1,  32,  87,  63],
       [171,   1,  40,  87,  13],
       [172,   1,  28,  87,  75],
       [173,   1,  36,  87,  10],
       [174,   1,  36,  87,  92],
       [175,   0,  52,  88,  13],
       [176,   0,  30,  88,  86],
       [177,   1,  58,  88,  15],
       [178,   1,  27,  88,  69],
       [179,   1,  59,  93,  14],
       [180,   1,  35,  93,  90],
       [181,   0,  37,  97,  32],
       [182,   0,  32,  97,  86],
       [183,   1,  46,  98,  15],
       [184,   0,  29,  98,  88],
       [185,   0,  41,  99,  39],
       [186,   1,  30,  99,  97],
       [187,   0,  54, 101,  24],
       [188,   1,  28, 101,  68],
       [189,   0,  41, 103,  17],
       [190,   0,  36, 103,  85],
       [191,   0,  34, 103,  23],
       [192,   0,  32, 103,  69],
       [193,   1,  33, 113,   8],
       [194,   0,  38, 113,  91],
       [195,   0,  47, 120,  16],
       [196,   0,  35, 120,  79],
       [197,   0,  45, 126,  28],
       [198,   1,  32, 126,  74],
       [199,   1,  32, 137,  18],
       [200,   1,  30, 137,  83]])

In [148]:
data_new.shape

(200, 5)

In [149]:
data_new.ndim

2

### Understand Customer Demographics

In [150]:
header = ['id', 'Gender', 'Age', 'AnnualIncome','Spending']

In [151]:
np.mean(data_new,axis=0)

array([100.5 ,   0.44,  38.85,  60.56,  50.2 ])

We can ignore the first 2 number as it is meaningless for id and gender. The average age is 38.85, average annual income is 60.56k and average spending score is 50.2.

In [152]:
# Extract and filter male customer and female customer
male_customer = data_new[data_new[:,1] == 1]
female_customer = data_new[data_new[:,1] == 0]

In [153]:
# Extract the last 3 columns of age, income and spending score
male_customer  = male_customer[:,2:]
female_customer  = female_customer[:,2:]

### Male Customer Analysis

In [154]:
np.mean(male_customer, axis = 0)

array([39.80681818, 62.22727273, 48.51136364])

For male customer, average age is 39.80, average income is 62.23K and average spending score is 48.5.

In [155]:
np.median(male_customer, axis = 0)

array([37. , 62.5, 50. ])

The median show relatively similar data. This shows that spending distribution is fairly distributed.

In [156]:
np.argmin(male_customer[:,-1])

67

In [157]:
male_customer[np.argmin(male_customer[:,-1])]

array([37, 78,  1])

In [158]:
np.argmax(male_customer[:,-1])

62

In [159]:
male_customer[np.argmax(male_customer[:,-1])]

array([28, 77, 97])

For male customer, minimum spending score is 1, he is a 37 year old with income of 78k. The highest spender is a 28 year old with income of 77k. His spending score is 97.

### Female Customer Analysis

In [160]:
np.mean(female_customer, axis = 0)

array([38.09821429, 59.25      , 51.52678571])

For female customer, average age is 38.1, average income is 59.25K and average spending score is 48.5.

In [161]:
np.median(female_customer, axis = 0)

array([35., 60., 50.])

The median is also very near to the mean, showing even distribution.

In [162]:
female_customer[np.argmin(female_customer[:,-1])]

array([46, 25,  5])

In [163]:
female_customer[np.argmax(female_customer[:,-1])]

array([35, 19, 99])

For female customer, minimum spending score is 5, she is a 46 year old with income of 19k. The highest spender is a 35 year old with income of 19Kk. Her spending score is 99.

In [164]:
np.sum(male_customer[:,2] > 75)

15

In [165]:
np.sum(female_customer[:,2] > 75)

23

There are more female customer with spending score more than 75 compared to male customer. This shows that female customer has more spending score.

In conclusion, there are more female high spender compare to mal spender. Average income is around 60K which is not high. This indicate that high spender is not necessary with high income and is about. Average age for both male and female customer is about 40 years old. This is also inline with the total average.

###  Identify High-Value Customers

In [166]:
# Check if filter is correct
data_new[:,-1] > 80

array([False,  True, False, False, False, False, False,  True, False,
       False, False,  True, False, False, False, False, False, False,
       False,  True, False, False, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False,  True,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False,  True, False, False, False, False, False, False, False,
        True, False, False, False, False, False,  True, False,  True,
       False,  True, False, False, False,  True, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
       False,  True, False, False, False,  True, False, False, False,
       False, False,  True, False,  True, False, False, False,  True,
       False,  True, False,  True, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False, False,
       False,  True])

In [167]:
# Display with filter
high_score = data_new[data_new[:,-1] > 80] 
high_score

array([[  2,   1,  21,  15,  81],
       [  8,   0,  23,  18,  94],
       [ 12,   0,  35,  19,  99],
       [ 20,   0,  35,  23,  98],
       [ 26,   1,  29,  28,  82],
       [ 30,   0,  23,  29,  87],
       [ 34,   1,  18,  33,  92],
       [ 36,   0,  21,  33,  81],
       [ 42,   1,  24,  38,  92],
       [124,   1,  39,  69,  91],
       [128,   1,  40,  71,  95],
       [136,   0,  29,  73,  88],
       [142,   1,  32,  75,  93],
       [144,   0,  32,  76,  87],
       [146,   1,  28,  77,  97],
       [150,   1,  34,  78,  90],
       [152,   1,  39,  78,  88],
       [156,   0,  27,  78,  89],
       [162,   0,  29,  79,  83],
       [164,   0,  31,  81,  93],
       [168,   0,  33,  86,  95],
       [174,   1,  36,  87,  92],
       [176,   0,  30,  88,  86],
       [180,   1,  35,  93,  90],
       [182,   0,  32,  97,  86],
       [184,   0,  29,  98,  88],
       [186,   1,  30,  99,  97],
       [190,   0,  36, 103,  85],
       [194,   0,  38, 113,  91],
       [200,   1,  30, 137,  83]])

In [168]:
np.mean(high_score, axis=0)

array([121.6       ,   0.46666667,  30.6       ,  69.06666667,
        89.76666667])

In [169]:
header

['id', 'Gender', 'Age', 'AnnualIncome', 'Spending']

Average income for the top spender is 69K.

In [170]:
np.argsort(high_score[:,-1])

array([ 0,  7,  4, 18, 29, 27, 24, 22,  5, 13, 25, 16, 11, 17, 15, 23, 28,
        9, 21,  8,  6, 19, 12,  1, 10, 20, 26, 14,  3,  2])

In [171]:
high_score[np.argsort(high_score[:,-1])]

array([[  2,   1,  21,  15,  81],
       [ 36,   0,  21,  33,  81],
       [ 26,   1,  29,  28,  82],
       [162,   0,  29,  79,  83],
       [200,   1,  30, 137,  83],
       [190,   0,  36, 103,  85],
       [182,   0,  32,  97,  86],
       [176,   0,  30,  88,  86],
       [ 30,   0,  23,  29,  87],
       [144,   0,  32,  76,  87],
       [184,   0,  29,  98,  88],
       [152,   1,  39,  78,  88],
       [136,   0,  29,  73,  88],
       [156,   0,  27,  78,  89],
       [150,   1,  34,  78,  90],
       [180,   1,  35,  93,  90],
       [194,   0,  38, 113,  91],
       [124,   1,  39,  69,  91],
       [174,   1,  36,  87,  92],
       [ 42,   1,  24,  38,  92],
       [ 34,   1,  18,  33,  92],
       [164,   0,  31,  81,  93],
       [142,   1,  32,  75,  93],
       [  8,   0,  23,  18,  94],
       [128,   1,  40,  71,  95],
       [168,   0,  33,  86,  95],
       [186,   1,  30,  99,  97],
       [146,   1,  28,  77,  97],
       [ 20,   0,  35,  23,  98],
       [ 12,   0,  35,  19,  99]])

In [172]:
sorted_high_score = high_score[np.argsort(high_score[:,-1])][::-1]
sorted_high_score

array([[ 12,   0,  35,  19,  99],
       [ 20,   0,  35,  23,  98],
       [146,   1,  28,  77,  97],
       [186,   1,  30,  99,  97],
       [168,   0,  33,  86,  95],
       [128,   1,  40,  71,  95],
       [  8,   0,  23,  18,  94],
       [142,   1,  32,  75,  93],
       [164,   0,  31,  81,  93],
       [ 34,   1,  18,  33,  92],
       [ 42,   1,  24,  38,  92],
       [174,   1,  36,  87,  92],
       [124,   1,  39,  69,  91],
       [194,   0,  38, 113,  91],
       [180,   1,  35,  93,  90],
       [150,   1,  34,  78,  90],
       [156,   0,  27,  78,  89],
       [136,   0,  29,  73,  88],
       [152,   1,  39,  78,  88],
       [184,   0,  29,  98,  88],
       [144,   0,  32,  76,  87],
       [ 30,   0,  23,  29,  87],
       [176,   0,  30,  88,  86],
       [182,   0,  32,  97,  86],
       [190,   0,  36, 103,  85],
       [200,   1,  30, 137,  83],
       [162,   0,  29,  79,  83],
       [ 26,   1,  29,  28,  82],
       [ 36,   0,  21,  33,  81],
       [  2,   1,  21,  15,  81]])

- https://stackoverflow.com/questions/2828059/sorting-arrays-in-numpy-by-column
- https://stackoverflow.com/questions/26984414/efficiently-sorting-a-numpy-array-in-descending-order

In [173]:
top_10 = sorted_high_score[:10,:]
top_10

array([[ 12,   0,  35,  19,  99],
       [ 20,   0,  35,  23,  98],
       [146,   1,  28,  77,  97],
       [186,   1,  30,  99,  97],
       [168,   0,  33,  86,  95],
       [128,   1,  40,  71,  95],
       [  8,   0,  23,  18,  94],
       [142,   1,  32,  75,  93],
       [164,   0,  31,  81,  93],
       [ 34,   1,  18,  33,  92]])

In [174]:
np.mean(top_10, axis = 0)

array([100.8,   0.5,  30.5,  58.2,  95.3])

The average income of the top 10 customer is only 58K. Average age is only 31 years old. The top spender is a 35 year old female with income of only 19K. The number of male and female customer is even. The oldest top spender is a 40 year old male with income of 71K.

In conclusion, the top spenders average income is inline with total average income. The average age of the top customer is lower then the total average,

### Explore Relationships Between Features

In [175]:
data_new[:10]

array([[ 1,  1, 19, 15, 39],
       [ 2,  1, 21, 15, 81],
       [ 3,  0, 20, 16,  6],
       [ 4,  0, 23, 16, 77],
       [ 5,  0, 31, 17, 40],
       [ 6,  0, 22, 17, 76],
       [ 7,  0, 35, 18,  6],
       [ 8,  0, 23, 18, 94],
       [ 9,  1, 64, 19,  3],
       [10,  0, 30, 19, 72]])

In [176]:
header

['id', 'Gender', 'Age', 'AnnualIncome', 'Spending']

In [177]:
age = data_new[:,2:3].ravel()
age

array([19, 21, 20, 23, 31, 22, 35, 23, 64, 30, 67, 35, 58, 24, 37, 22, 35,
       20, 52, 35, 35, 25, 46, 31, 54, 29, 45, 35, 40, 23, 60, 21, 53, 18,
       49, 21, 42, 30, 36, 20, 65, 24, 48, 31, 49, 24, 50, 27, 29, 31, 49,
       33, 31, 59, 50, 47, 51, 69, 27, 53, 70, 19, 67, 54, 63, 18, 43, 68,
       19, 32, 70, 47, 60, 60, 59, 26, 45, 40, 23, 49, 57, 38, 67, 46, 21,
       48, 55, 22, 34, 50, 68, 18, 48, 40, 32, 24, 47, 27, 48, 20, 23, 49,
       67, 26, 49, 21, 66, 54, 68, 66, 65, 19, 38, 19, 18, 19, 63, 49, 51,
       50, 27, 38, 40, 39, 23, 31, 43, 40, 59, 38, 47, 39, 25, 31, 20, 29,
       44, 32, 19, 35, 57, 32, 28, 32, 25, 28, 48, 32, 34, 34, 43, 39, 44,
       38, 47, 27, 37, 30, 34, 30, 56, 29, 19, 31, 50, 36, 42, 33, 36, 32,
       40, 28, 36, 36, 52, 30, 58, 27, 59, 35, 37, 32, 46, 29, 41, 30, 54,
       28, 41, 36, 34, 32, 33, 38, 47, 35, 45, 32, 32, 30])

In [178]:
spending = data_new[:,-1]
spending

array([39, 81,  6, 77, 40, 76,  6, 94,  3, 72, 14, 99, 15, 77, 13, 79, 35,
       66, 29, 98, 35, 73,  5, 73, 14, 82, 32, 61, 31, 87,  4, 73,  4, 92,
       14, 81, 17, 73, 26, 75, 35, 92, 36, 61, 28, 65, 55, 47, 42, 42, 52,
       60, 54, 60, 45, 41, 50, 46, 51, 46, 56, 55, 52, 59, 51, 59, 50, 48,
       59, 47, 55, 42, 49, 56, 47, 54, 53, 48, 52, 42, 51, 55, 41, 44, 57,
       46, 58, 55, 60, 46, 55, 41, 49, 40, 42, 52, 47, 50, 42, 49, 41, 48,
       59, 55, 56, 42, 50, 46, 43, 48, 52, 54, 42, 46, 48, 50, 43, 59, 43,
       57, 56, 40, 58, 91, 29, 77, 35, 95, 11, 75,  9, 75, 34, 71,  5, 88,
        7, 73, 10, 72,  5, 93, 40, 87, 12, 97, 36, 74, 22, 90, 17, 88, 20,
       76, 16, 89,  1, 78,  1, 73, 35, 83,  5, 93, 26, 75, 20, 95, 27, 63,
       13, 75, 10, 92, 13, 86, 15, 69, 14, 90, 32, 86, 15, 88, 39, 97, 24,
       68, 17, 85, 23, 69,  8, 91, 16, 79, 28, 74, 18, 83])

In [179]:
income = data_new[:,-2]
income

array([ 15,  15,  16,  16,  17,  17,  18,  18,  19,  19,  19,  19,  20,
        20,  20,  20,  21,  21,  23,  23,  24,  24,  25,  25,  28,  28,
        28,  28,  29,  29,  30,  30,  33,  33,  33,  33,  34,  34,  37,
        37,  38,  38,  39,  39,  39,  39,  40,  40,  40,  40,  42,  42,
        43,  43,  43,  43,  44,  44,  46,  46,  46,  46,  47,  47,  48,
        48,  48,  48,  48,  48,  49,  49,  50,  50,  54,  54,  54,  54,
        54,  54,  54,  54,  54,  54,  54,  54,  57,  57,  58,  58,  59,
        59,  60,  60,  60,  60,  60,  60,  61,  61,  62,  62,  62,  62,
        62,  62,  63,  63,  63,  63,  63,  63,  64,  64,  65,  65,  65,
        65,  67,  67,  67,  67,  69,  69,  70,  70,  71,  71,  71,  71,
        71,  71,  72,  72,  73,  73,  73,  73,  74,  74,  75,  75,  76,
        76,  77,  77,  77,  77,  78,  78,  78,  78,  78,  78,  78,  78,
        78,  78,  78,  78,  79,  79,  81,  81,  85,  85,  86,  86,  87,
        87,  87,  87,  87,  87,  88,  88,  88,  88,  93,  93,  97,  97,
        98,  98,  99,  99, 101, 101, 103, 103, 103, 103, 113, 113, 120,
       120, 126, 126, 137, 137])

In [180]:
age_spending = np.corrcoef(age,spending)
age_spending

array([[ 1.        , -0.32722685],
       [-0.32722685,  1.        ]])

This shows that there is an inverse relationship between age and spending. Our previous analysis also shows that the top spender are not the oldest.

In [181]:
income_spending = np.corrcoef(income, spending)
income_spending

array([[1.        , 0.00990285],
       [0.00990285, 1.        ]])

This shows that there is very little correlation between spending score and income.

In [182]:
age_income = np.corrcoef(age,income)
age_income

array([[ 1.        , -0.01239804],
       [-0.01239804,  1.        ]])

This shows that there is very little correlation between age and income.

In [183]:
# Filter young adults
(data_new[:,2] > 18) & (data_new[:,2] < 25)

array([ True,  True,  True,  True, False,  True, False,  True, False,
       False, False, False, False,  True, False,  True, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False,  True, False, False, False,  True,
       False, False, False,  True, False,  True, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False,  True, False, False,  True, False, False,
       False, False, False, False, False,  True, False, False, False,
        True,  True, False, False, False, False,  True, False, False,
       False, False, False,  True, False,  True, False,  True, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [184]:
data_new[(data_new[:,2] > 18) & (data_new[:,2] < 25)]

array([[  1,   1,  19,  15,  39],
       [  2,   1,  21,  15,  81],
       [  3,   0,  20,  16,   6],
       [  4,   0,  23,  16,  77],
       [  6,   0,  22,  17,  76],
       [  8,   0,  23,  18,  94],
       [ 14,   0,  24,  20,  77],
       [ 16,   1,  22,  20,  79],
       [ 18,   1,  20,  21,  66],
       [ 30,   0,  23,  29,  87],
       [ 32,   0,  21,  30,  73],
       [ 36,   0,  21,  33,  81],
       [ 40,   0,  20,  37,  75],
       [ 42,   1,  24,  38,  92],
       [ 46,   0,  24,  39,  65],
       [ 62,   1,  19,  46,  55],
       [ 69,   1,  19,  48,  59],
       [ 79,   0,  23,  54,  52],
       [ 85,   0,  21,  54,  57],
       [ 88,   0,  22,  57,  55],
       [ 96,   1,  24,  60,  52],
       [100,   1,  20,  61,  49],
       [101,   0,  23,  62,  41],
       [106,   0,  21,  62,  42],
       [112,   0,  19,  63,  54],
       [114,   1,  19,  64,  46],
       [116,   0,  19,  65,  50],
       [125,   0,  23,  70,  29],
       [135,   1,  20,  73,   5],
       [139,   1,  19,  74,  10],
       [163,   1,  19,  81,   5]])

In [185]:
young_adults = data_new[(data_new[:,2] > 18) & (data_new[:,2] < 25)]
young_adults

array([[  1,   1,  19,  15,  39],
       [  2,   1,  21,  15,  81],
       [  3,   0,  20,  16,   6],
       [  4,   0,  23,  16,  77],
       [  6,   0,  22,  17,  76],
       [  8,   0,  23,  18,  94],
       [ 14,   0,  24,  20,  77],
       [ 16,   1,  22,  20,  79],
       [ 18,   1,  20,  21,  66],
       [ 30,   0,  23,  29,  87],
       [ 32,   0,  21,  30,  73],
       [ 36,   0,  21,  33,  81],
       [ 40,   0,  20,  37,  75],
       [ 42,   1,  24,  38,  92],
       [ 46,   0,  24,  39,  65],
       [ 62,   1,  19,  46,  55],
       [ 69,   1,  19,  48,  59],
       [ 79,   0,  23,  54,  52],
       [ 85,   0,  21,  54,  57],
       [ 88,   0,  22,  57,  55],
       [ 96,   1,  24,  60,  52],
       [100,   1,  20,  61,  49],
       [101,   0,  23,  62,  41],
       [106,   0,  21,  62,  42],
       [112,   0,  19,  63,  54],
       [114,   1,  19,  64,  46],
       [116,   0,  19,  65,  50],
       [125,   0,  23,  70,  29],
       [135,   1,  20,  73,   5],
       [139,   1,  19,  74,  10],
       [163,   1,  19,  81,   5]])

In [186]:
young_adults.mean(axis=0)

array([64.12903226,  0.41935484, 21.19354839, 43.80645161, 55.77419355])

In [187]:
older_adults = data_new[data_new[:,2] > 25]

In [188]:
older_adults.mean(axis = 0)

array([108.05555556,   0.43209877,  43.        ,  64.04938272,
        49.08641975])

Average income of young adults is 44K with average spending score of 55.77. Adults older than 25 has average income of 64K with spending score of 49. This shows that young adults has high spending score although the income is lower.

### Customer Segmentation

In [189]:
header

['id', 'Gender', 'Age', 'AnnualIncome', 'Spending']

In [190]:
data_new[(data_new[:,-1] >= 1) & (data_new[:,-1] <= 33)]

array([[  3,   0,  20,  16,   6],
       [  7,   0,  35,  18,   6],
       [  9,   1,  64,  19,   3],
       [ 11,   1,  67,  19,  14],
       [ 13,   0,  58,  20,  15],
       [ 15,   1,  37,  20,  13],
       [ 19,   1,  52,  23,  29],
       [ 23,   0,  46,  25,   5],
       [ 25,   0,  54,  28,  14],
       [ 27,   0,  45,  28,  32],
       [ 29,   0,  40,  29,  31],
       [ 31,   1,  60,  30,   4],
       [ 33,   1,  53,  33,   4],
       [ 35,   0,  49,  33,  14],
       [ 37,   0,  42,  34,  17],
       [ 39,   0,  36,  37,  26],
       [ 45,   0,  49,  39,  28],
       [125,   0,  23,  70,  29],
       [129,   1,  59,  71,  11],
       [131,   1,  47,  71,   9],
       [135,   1,  20,  73,   5],
       [137,   0,  44,  73,   7],
       [139,   1,  19,  74,  10],
       [141,   0,  57,  75,   5],
       [145,   1,  25,  77,  12],
       [149,   0,  34,  78,  22],
       [151,   1,  43,  78,  17],
       [153,   0,  44,  78,  20],
       [155,   0,  47,  78,  16],
       [157,   1,  37,  78,   1],
       [159,   1,  34,  78,   1],
       [163,   1,  19,  81,   5],
       [165,   1,  50,  85,  26],
       [167,   1,  42,  86,  20],
       [169,   0,  36,  87,  27],
       [171,   1,  40,  87,  13],
       [173,   1,  36,  87,  10],
       [175,   0,  52,  88,  13],
       [177,   1,  58,  88,  15],
       [179,   1,  59,  93,  14],
       [181,   0,  37,  97,  32],
       [183,   1,  46,  98,  15],
       [187,   0,  54, 101,  24],
       [189,   0,  41, 103,  17],
       [191,   0,  34, 103,  23],
       [193,   1,  33, 113,   8],
       [195,   0,  47, 120,  16],
       [197,   0,  45, 126,  28],
       [199,   1,  32, 137,  18]])

In [191]:
low = data_new[(data_new[:,-1] >= 1) & (data_new[:,-1] <= 33)]

In [192]:
data_new[(data_new[:,-1] >= 34) & (data_new[:,-1] <= 66)]

array([[  1,   1,  19,  15,  39],
       [  5,   0,  31,  17,  40],
       [ 17,   0,  35,  21,  35],
       [ 18,   1,  20,  21,  66],
       [ 21,   1,  35,  24,  35],
       [ 28,   1,  35,  28,  61],
       [ 41,   0,  65,  38,  35],
       [ 43,   1,  48,  39,  36],
       [ 44,   0,  31,  39,  61],
       [ 46,   0,  24,  39,  65],
       [ 47,   0,  50,  40,  55],
       [ 48,   0,  27,  40,  47],
       [ 49,   0,  29,  40,  42],
       [ 50,   0,  31,  40,  42],
       [ 51,   0,  49,  42,  52],
       [ 52,   1,  33,  42,  60],
       [ 53,   0,  31,  43,  54],
       [ 54,   1,  59,  43,  60],
       [ 55,   0,  50,  43,  45],
       [ 56,   1,  47,  43,  41],
       [ 57,   0,  51,  44,  50],
       [ 58,   1,  69,  44,  46],
       [ 59,   0,  27,  46,  51],
       [ 60,   1,  53,  46,  46],
       [ 61,   1,  70,  46,  56],
       [ 62,   1,  19,  46,  55],
       [ 63,   0,  67,  47,  52],
       [ 64,   0,  54,  47,  59],
       [ 65,   1,  63,  48,  51],
       [ 66,   1,  18,  48,  59],
       [ 67,   0,  43,  48,  50],
       [ 68,   0,  68,  48,  48],
       [ 69,   1,  19,  48,  59],
       [ 70,   0,  32,  48,  47],
       [ 71,   1,  70,  49,  55],
       [ 72,   0,  47,  49,  42],
       [ 73,   0,  60,  50,  49],
       [ 74,   0,  60,  50,  56],
       [ 75,   1,  59,  54,  47],
       [ 76,   1,  26,  54,  54],
       [ 77,   0,  45,  54,  53],
       [ 78,   1,  40,  54,  48],
       [ 79,   0,  23,  54,  52],
       [ 80,   0,  49,  54,  42],
       [ 81,   1,  57,  54,  51],
       [ 82,   1,  38,  54,  55],
       [ 83,   1,  67,  54,  41],
       [ 84,   0,  46,  54,  44],
       [ 85,   0,  21,  54,  57],
       [ 86,   1,  48,  54,  46],
       [ 87,   0,  55,  57,  58],
       [ 88,   0,  22,  57,  55],
       [ 89,   0,  34,  58,  60],
       [ 90,   0,  50,  58,  46],
       [ 91,   0,  68,  59,  55],
       [ 92,   1,  18,  59,  41],
       [ 93,   1,  48,  60,  49],
       [ 94,   0,  40,  60,  40],
       [ 95,   0,  32,  60,  42],
       [ 96,   1,  24,  60,  52],
       [ 97,   0,  47,  60,  47],
       [ 98,   0,  27,  60,  50],
       [ 99,   1,  48,  61,  42],
       [100,   1,  20,  61,  49],
       [101,   0,  23,  62,  41],
       [102,   0,  49,  62,  48],
       [103,   1,  67,  62,  59],
       [104,   1,  26,  62,  55],
       [105,   1,  49,  62,  56],
       [106,   0,  21,  62,  42],
       [107,   0,  66,  63,  50],
       [108,   1,  54,  63,  46],
       [109,   1,  68,  63,  43],
       [110,   1,  66,  63,  48],
       [111,   1,  65,  63,  52],
       [112,   0,  19,  63,  54],
       [113,   0,  38,  64,  42],
       [114,   1,  19,  64,  46],
       [115,   0,  18,  65,  48],
       [116,   0,  19,  65,  50],
       [117,   0,  63,  65,  43],
       [118,   0,  49,  65,  59],
       [119,   0,  51,  67,  43],
       [120,   0,  50,  67,  57],
       [121,   1,  27,  67,  56],
       [122,   0,  38,  67,  40],
       [123,   0,  40,  69,  58],
       [127,   1,  43,  71,  35],
       [133,   0,  25,  72,  34],
       [143,   0,  28,  76,  40],
       [147,   1,  48,  77,  36],
       [161,   0,  56,  79,  35],
       [170,   1,  32,  87,  63],
       [185,   0,  41,  99,  39]])

In [193]:
medium = data_new[(data_new[:,-1] >= 34) & (data_new[:,-1] <= 66)]

In [194]:
high = data_new[(data_new[:,-1] >= 67) & (data_new[:,-1] <= 100)]

In [195]:
header

['id', 'Gender', 'Age', 'AnnualIncome', 'Spending']

In [196]:
low.mean(axis=0)

array([115.53061224,   0.48979592,  42.87755102,  67.        ,
        15.30612245])

For the group with lower spending score, the average age is 43 years old with average annual income of 67K.

In [197]:
medium.mean(axis=0)

array([83.77659574,  0.42553191, 42.0106383 , 53.86170213, 48.89361702])

For the group with medium spending score, the average age is 42 years old with average annual income of 53K.

In [198]:
high.mean(axis=0)

array([115.15789474,   0.42105263,  30.1754386 ,  66.07017544,
        82.35087719])

For the group with high spending score, the average age is 30 years old with average annual income of 66K.

In conclusion, the high spending group belongs to the younger working adults specially the group 40 years old and below. Their income is slightly above average.

### Find Behavioral Similarities

In [199]:
data_new[:10]

array([[ 1,  1, 19, 15, 39],
       [ 2,  1, 21, 15, 81],
       [ 3,  0, 20, 16,  6],
       [ 4,  0, 23, 16, 77],
       [ 5,  0, 31, 17, 40],
       [ 6,  0, 22, 17, 76],
       [ 7,  0, 35, 18,  6],
       [ 8,  0, 23, 18, 94],
       [ 9,  1, 64, 19,  3],
       [10,  0, 30, 19, 72]])

In [200]:
header

['id', 'Gender', 'Age', 'AnnualIncome', 'Spending']

In [201]:
avg = np.mean(data_new, axis=0)

In [202]:
std_dev = np.std(data_new, axis=0)

In [203]:
data_norm = (data_new - avg) / std_dev
data_norm

array([[-1.7234121 ,  1.12815215, -1.42456879, -1.73899919, -0.43480148],
       [-1.70609137,  1.12815215, -1.28103541, -1.73899919,  1.19570407],
       [-1.68877065, -0.88640526, -1.3528021 , -1.70082976, -1.71591298],
       [-1.67144992, -0.88640526, -1.13750203, -1.70082976,  1.04041783],
       [-1.6541292 , -0.88640526, -0.56336851, -1.66266033, -0.39597992],
       [-1.63680847, -0.88640526, -1.20926872, -1.66266033,  1.00159627],
       [-1.61948775, -0.88640526, -0.27630176, -1.62449091, -1.71591298],
       [-1.60216702, -0.88640526, -1.13750203, -1.62449091,  1.70038436],
       [-1.5848463 ,  1.12815215,  1.80493225, -1.58632148, -1.83237767],
       [-1.56752558, -0.88640526, -0.6351352 , -1.58632148,  0.84631002],
       [-1.55020485,  1.12815215,  2.02023231, -1.58632148, -1.4053405 ],
       [-1.53288413, -0.88640526, -0.27630176, -1.58632148,  1.89449216],
       [-1.5155634 , -0.88640526,  1.37433211, -1.54815205, -1.36651894],
       [-1.49824268, -0.88640526, -1.06573534, -1.54815205,  1.04041783],
       [-1.48092195,  1.12815215, -0.13276838, -1.54815205, -1.44416206],
       [-1.46360123,  1.12815215, -1.20926872, -1.54815205,  1.11806095],
       [-1.4462805 , -0.88640526, -0.27630176, -1.50998262, -0.59008772],
       [-1.42895978,  1.12815215, -1.3528021 , -1.50998262,  0.61338066],
       [-1.41163905,  1.12815215,  0.94373197, -1.43364376, -0.82301709],
       [-1.39431833, -0.88640526, -0.27630176, -1.43364376,  1.8556706 ],
       [-1.3769976 ,  1.12815215, -0.27630176, -1.39547433, -0.59008772],
       [-1.35967688,  1.12815215, -0.99396865, -1.39547433,  0.88513158],
       [-1.34235616, -0.88640526,  0.51313183, -1.3573049 , -1.75473454],
       [-1.32503543,  1.12815215, -0.56336851, -1.3573049 ,  0.88513158],
       [-1.30771471, -0.88640526,  1.08726535, -1.24279661, -1.4053405 ],
       [-1.29039398,  1.12815215, -0.70690189, -1.24279661,  1.23452563],
       [-1.27307326, -0.88640526,  0.44136514, -1.24279661, -0.7065524 ],
       [-1.25575253,  1.12815215, -0.27630176, -1.24279661,  0.41927286],
       [-1.23843181, -0.88640526,  0.08253169, -1.20462718, -0.74537397],
       [-1.22111108, -0.88640526, -1.13750203, -1.20462718,  1.42863343],
       [-1.20379036,  1.12815215,  1.51786549, -1.16645776, -1.7935561 ],
       [-1.18646963, -0.88640526, -1.28103541, -1.16645776,  0.88513158],
       [-1.16914891,  1.12815215,  1.01549866, -1.05194947, -1.7935561 ],
       [-1.15182818,  1.12815215, -1.49633548, -1.05194947,  1.62274124],
       [-1.13450746, -0.88640526,  0.7284319 , -1.05194947, -1.4053405 ],
       [-1.11718674, -0.88640526, -1.28103541, -1.05194947,  1.19570407],
       [-1.09986601, -0.88640526,  0.22606507, -1.01378004, -1.28887582],
       [-1.08254529, -0.88640526, -0.6351352 , -1.01378004,  0.88513158],
       [-1.06522456, -0.88640526, -0.20453507, -0.89927175, -0.93948177],
       [-1.04790384, -0.88640526, -1.3528021 , -0.89927175,  0.96277471],
       [-1.03058311, -0.88640526,  1.87669894, -0.86110232, -0.59008772],
       [-1.01326239,  1.12815215, -1.06573534, -0.86110232,  1.62274124],
       [-0.99594166,  1.12815215,  0.65666521, -0.82293289, -0.55126616],
       [-0.97862094, -0.88640526, -0.56336851, -0.82293289,  0.41927286],
       [-0.96130021, -0.88640526,  0.7284319 , -0.82293289, -0.86183865],
       [-0.94397949, -0.88640526, -1.06573534, -0.82293289,  0.5745591 ],
       [-0.92665877, -0.88640526,  0.80019859, -0.78476346,  0.18634349],
       [-0.90933804, -0.88640526, -0.85043527, -0.78476346, -0.12422899],
       [-0.89201732, -0.88640526, -0.70690189, -0.78476346, -0.3183368 ],
       [-0.87469659, -0.88640526, -0.56336851, -0.78476346, -0.3183368 ],
       [-0.85737587, -0.88640526,  0.7284319 , -0.70842461,  0.06987881],
       [-0.84005514,  1.12815215, -0.41983513, -0.70842461,  0.38045129],
       [-0.82273442, -0.88640526, -0.56336851, -0.67025518,  0.14752193],
       [-0.80541369,  1.12815215,  1.4460988 , -0.67025518,  0.38045129],
       [-0.78809297, -0.88640526,  0.80019859, -0.67025518, -0.20187212],
       [-0.77077224,  1.12815215,  0.58489852, -0.67025518, -0.35715836],
       [-0.75345152, -0.88640526,  0.87196528, -0.63208575, -0.00776431],
       [-0.73613079,  1.12815215,  2.16376569, -0.63208575, -0.16305055],
       [-0.71881007, -0.88640526, -0.85043527, -0.55574689,  0.03105725],
       [-0.70148935,  1.12815215,  1.01549866, -0.55574689, -0.16305055],
       [-0.68416862,  1.12815215,  2.23553238, -0.55574689,  0.22516505],
       [-0.6668479 ,  1.12815215, -1.42456879, -0.55574689,  0.18634349],
       [-0.64952717, -0.88640526,  2.02023231, -0.51757746,  0.06987881],
       [-0.63220645, -0.88640526,  1.08726535, -0.51757746,  0.34162973],
       [-0.61488572,  1.12815215,  1.73316556, -0.47940803,  0.03105725],
       [-0.597565  ,  1.12815215, -1.49633548, -0.47940803,  0.34162973],
       [-0.58024427, -0.88640526,  0.29783176, -0.47940803, -0.00776431],
       [-0.56292355, -0.88640526,  2.091999  , -0.47940803, -0.08540743],
       [-0.54560282,  1.12815215, -1.42456879, -0.47940803,  0.34162973],
       [-0.5282821 , -0.88640526, -0.49160182, -0.47940803, -0.12422899],
       [-0.51096138,  1.12815215,  2.23553238, -0.4412386 ,  0.18634349],
       [-0.49364065, -0.88640526,  0.58489852, -0.4412386 , -0.3183368 ],
       [-0.47631993, -0.88640526,  1.51786549, -0.40306917, -0.04658587],
       [-0.4589992 , -0.88640526,  1.51786549, -0.40306917,  0.22516505],
       [-0.44167848,  1.12815215,  1.4460988 , -0.25039146, -0.12422899],
       [-0.42435775,  1.12815215, -0.92220196, -0.25039146,  0.14752193],
       [-0.40703703, -0.88640526,  0.44136514, -0.25039146,  0.10870037],
       [-0.3897163 ,  1.12815215,  0.08253169, -0.25039146, -0.08540743],
       [-0.37239558, -0.88640526, -1.13750203, -0.25039146,  0.06987881],
       [-0.35507485, -0.88640526,  0.7284319 , -0.25039146, -0.3183368 ],
       [-0.33775413,  1.12815215,  1.30256542, -0.25039146,  0.03105725],
       [-0.3204334 ,  1.12815215, -0.06100169, -0.25039146,  0.18634349],
       [-0.30311268,  1.12815215,  2.02023231, -0.25039146, -0.35715836],
       [-0.28579196, -0.88640526,  0.51313183, -0.25039146, -0.24069368],
       [-0.26847123, -0.88640526, -1.28103541, -0.25039146,  0.26398661],
       [-0.25115051,  1.12815215,  0.65666521, -0.25039146, -0.16305055],
       [-0.23382978, -0.88640526,  1.15903204, -0.13588317,  0.30280817],
       [-0.21650906, -0.88640526, -1.20926872, -0.13588317,  0.18634349],
       [-0.19918833, -0.88640526, -0.34806844, -0.09771374,  0.38045129],
       [-0.18186761, -0.88640526,  0.80019859, -0.09771374, -0.16305055],
       [-0.16454688, -0.88640526,  2.091999  , -0.05954431,  0.18634349],
       [-0.14722616,  1.12815215, -1.49633548, -0.05954431, -0.35715836],
       [-0.12990543,  1.12815215,  0.65666521, -0.02137488, -0.04658587],
       [-0.11258471, -0.88640526,  0.08253169, -0.02137488, -0.39597992],
       [-0.09526399, -0.88640526, -0.49160182, -0.02137488, -0.3183368 ],
       [-0.07794326,  1.12815215, -1.06573534, -0.02137488,  0.06987881],
       [-0.06062254, -0.88640526,  0.58489852, -0.02137488, -0.12422899],
       [-0.04330181, -0.88640526, -0.85043527, -0.02137488, -0.00776431],
       [-0.02598109,  1.12815215,  0.65666521,  0.01679455, -0.3183368 ],
       [-0.00866036,  1.12815215, -1.3528021 ,  0.01679455, -0.04658587],
       [ 0.00866036, -0.88640526, -1.13750203,  0.05496398, -0.35715836],
       [ 0.02598109, -0.88640526,  0.7284319 ,  0.05496398, -0.08540743],
       [ 0.04330181,  1.12815215,  2.02023231,  0.05496398,  0.34162973],
       [ 0.06062254,  1.12815215, -0.92220196,  0.05496398,  0.18634349],
       [ 0.07794326,  1.12815215,  0.7284319 ,  0.05496398,  0.22516505],
       [ 0.09526399, -0.88640526, -1.28103541,  0.05496398, -0.3183368 ],
       [ 0.11258471, -0.88640526,  1.94846562,  0.09313341, -0.00776431],
       [ 0.12990543,  1.12815215,  1.08726535,  0.09313341, -0.16305055],
       [ 0.14722616,  1.12815215,  2.091999  ,  0.09313341, -0.27951524],
       [ 0.16454688,  1.12815215,  1.94846562,  0.09313341, -0.08540743],
       [ 0.18186761,  1.12815215,  1.87669894,  0.09313341,  0.06987881],
       [ 0.19918833, -0.88640526, -1.42456879,  0.09313341,  0.14752193],
       [ 0.21650906, -0.88640526, -0.06100169,  0.13130284, -0.3183368 ],
       [ 0.23382978,  1.12815215, -1.42456879,  0.13130284, -0.16305055],
       [ 0.25115051, -0.88640526, -1.49633548,  0.16947227, -0.08540743],
       [ 0.26847123, -0.88640526, -1.42456879,  0.16947227, -0.00776431],
       [ 0.28579196, -0.88640526,  1.73316556,  0.16947227, -0.27951524],
       [ 0.30311268, -0.88640526,  0.7284319 ,  0.16947227,  0.34162973],
       [ 0.3204334 , -0.88640526,  0.87196528,  0.24581112, -0.27951524],
       [ 0.33775413, -0.88640526,  0.80019859,  0.24581112,  0.26398661],
       [ 0.35507485,  1.12815215, -0.85043527,  0.24581112,  0.22516505],
       [ 0.37239558, -0.88640526, -0.06100169,  0.24581112, -0.39597992],
       [ 0.3897163 , -0.88640526,  0.08253169,  0.32214998,  0.30280817],
       [ 0.40703703,  1.12815215,  0.010765  ,  0.32214998,  1.58391968],
       [ 0.42435775, -0.88640526, -1.13750203,  0.36031941, -0.82301709],
       [ 0.44167848, -0.88640526, -0.56336851,  0.36031941,  1.04041783],
       [ 0.4589992 ,  1.12815215,  0.29783176,  0.39848884, -0.59008772],
       [ 0.47631993,  1.12815215,  0.08253169,  0.39848884,  1.73920592],
       [ 0.49364065,  1.12815215,  1.4460988 ,  0.39848884, -1.52180518],
       [ 0.51096138,  1.12815215, -0.06100169,  0.39848884,  0.96277471],
       [ 0.5282821 ,  1.12815215,  0.58489852,  0.39848884, -1.5994483 ],
       [ 0.54560282,  1.12815215,  0.010765  ,  0.39848884,  0.96277471],
       [ 0.56292355, -0.88640526, -0.99396865,  0.43665827, -0.62890928],
       [ 0.58024427, -0.88640526, -0.56336851,  0.43665827,  0.80748846],
       [ 0.597565  ,  1.12815215, -1.3528021 ,  0.4748277 , -1.75473454],
       [ 0.61488572, -0.88640526, -0.70690189,  0.4748277 ,  1.46745499],
       [ 0.63220645, -0.88640526,  0.36959845,  0.4748277 , -1.67709142],
       [ 0.64952717,  1.12815215, -0.49160182,  0.4748277 ,  0.88513158],
       [ 0.6668479 ,  1.12815215, -1.42456879,  0.51299713, -1.56062674],
       [ 0.68416862, -0.88640526, -0.27630176,  0.51299713,  0.84631002],
       [ 0.70148935, -0.88640526,  1.30256542,  0.55116656, -1.75473454],
       [ 0.71881007,  1.12815215, -0.49160182,  0.55116656,  1.6615628 ],
       [ 0.73613079, -0.88640526, -0.77866858,  0.58933599, -0.39597992],
       [ 0.75345152, -0.88640526, -0.49160182,  0.58933599,  1.42863343],
       [ 0.77077224,  1.12815215, -0.99396865,  0.62750542, -1.48298362],
       [ 0.78809297,  1.12815215, -0.77866858,  0.62750542,  1.81684904],
       [ 0.80541369,  1.12815215,  0.65666521,  0.62750542, -0.55126616],
       [ 0.82273442, -0.88640526, -0.49160182,  0.62750542,  0.92395314],
       [ 0.84005514, -0.88640526, -0.34806844,  0.66567484, -1.09476801],
       [ 0.85737587,  1.12815215, -0.34806844,  0.66567484,  1.54509812],
       [ 0.87469659,  1.12815215,  0.29783176,  0.66567484, -1.28887582],
       [ 0.89201732,  1.12815215,  0.010765  ,  0.66567484,  1.46745499],
       [ 0.90933804, -0.88640526,  0.36959845,  0.66567484, -1.17241113],
       [ 0.92665877, -0.88640526, -0.06100169,  0.66567484,  1.00159627],
       [ 0.94397949, -0.88640526,  0.58489852,  0.66567484, -1.32769738],
       [ 0.96130021, -0.88640526, -0.85043527,  0.66567484,  1.50627656],
       [ 0.97862094,  1.12815215, -0.13276838,  0.66567484, -1.91002079],
       [ 0.99594166, -0.88640526, -0.6351352 ,  0.66567484,  1.07923939],
       [ 1.01326239,  1.12815215, -0.34806844,  0.66567484, -1.91002079],
       [ 1.03058311, -0.88640526, -0.6351352 ,  0.66567484,  0.88513158],
       [ 1.04790384, -0.88640526,  1.23079873,  0.70384427, -0.59008772],
       [ 1.06522456, -0.88640526, -0.70690189,  0.70384427,  1.27334719],
       [ 1.08254529,  1.12815215, -1.42456879,  0.78018313, -1.75473454],
       [ 1.09986601, -0.88640526, -0.56336851,  0.78018313,  1.6615628 ],
       [ 1.11718674,  1.12815215,  0.80019859,  0.93286085, -0.93948177],
       [ 1.13450746, -0.88640526, -0.20453507,  0.93286085,  0.96277471],
       [ 1.15182818,  1.12815215,  0.22606507,  0.97103028, -1.17241113],
       [ 1.16914891, -0.88640526, -0.41983513,  0.97103028,  1.73920592],
       [ 1.18646963, -0.88640526, -0.20453507,  1.00919971, -0.90066021],
       [ 1.20379036,  1.12815215, -0.49160182,  1.00919971,  0.49691598],
       [ 1.22111108,  1.12815215,  0.08253169,  1.00919971, -1.44416206],
       [ 1.23843181,  1.12815215, -0.77866858,  1.00919971,  0.96277471],
       [ 1.25575253,  1.12815215, -0.20453507,  1.00919971, -1.56062674],
       [ 1.27307326,  1.12815215, -0.20453507,  1.00919971,  1.62274124],
       [ 1.29039398, -0.88640526,  0.94373197,  1.04736914, -1.44416206],
       [ 1.30771471, -0.88640526, -0.6351352 ,  1.04736914,  1.38981187],
       [ 1.32503543,  1.12815215,  1.37433211,  1.04736914, -1.36651894],
       [ 1.34235616,  1.12815215, -0.85043527,  1.04736914,  0.72984534],
       [ 1.35967688,  1.12815215,  1.4460988 ,  1.23821628, -1.4053405 ],
       [ 1.3769976 ,  1.12815215, -0.27630176,  1.23821628,  1.54509812],
       [ 1.39431833, -0.88640526, -0.13276838,  1.390894  , -0.7065524 ],
       [ 1.41163905, -0.88640526, -0.49160182,  1.390894  ,  1.38981187],
       [ 1.42895978,  1.12815215,  0.51313183,  1.42906343, -1.36651894],
       [ 1.4462805 , -0.88640526, -0.70690189,  1.42906343,  1.46745499],
       [ 1.46360123, -0.88640526,  0.15429838,  1.46723286, -0.43480148],
       [ 1.48092195,  1.12815215, -0.6351352 ,  1.46723286,  1.81684904],
       [ 1.49824268, -0.88640526,  1.08726535,  1.54357172, -1.01712489],
       [ 1.5155634 ,  1.12815215, -0.77866858,  1.54357172,  0.69102378],
       [ 1.53288413, -0.88640526,  0.15429838,  1.61991057, -1.28887582],
       [ 1.55020485, -0.88640526, -0.20453507,  1.61991057,  1.35099031],
       [ 1.56752558, -0.88640526, -0.34806844,  1.61991057, -1.05594645],
       [ 1.5848463 , -0.88640526, -0.49160182,  1.61991057,  0.72984534],
       [ 1.60216702,  1.12815215, -0.41983513,  2.00160487, -1.63826986],
       [ 1.61948775, -0.88640526, -0.06100169,  2.00160487,  1.58391968],
       [ 1.63680847, -0.88640526,  0.58489852,  2.26879087, -1.32769738],
       [ 1.6541292 , -0.88640526, -0.27630176,  2.26879087,  1.11806095],
       [ 1.67144992, -0.88640526,  0.44136514,  2.49780745, -0.86183865],
       [ 1.68877065,  1.12815215, -0.49160182,  2.49780745,  0.92395314],
       [ 1.70609137,  1.12815215, -0.49160182,  2.91767117, -1.25005425],
       [ 1.7234121 ,  1.12815215, -0.6351352 ,  2.91767117,  1.27334719]])

In [204]:
data_norm = data_norm[:, 2:]

In [205]:
data_norm.shape

(200, 3)

- https://www.geeksforgeeks.org/calculate-the-euclidean-distance-using-numpy/
- https://stackoverflow.com/questions/1401712/how-can-the-euclidean-distance-be-calculated-with-numpy
- https://www.kdnuggets.com/2023/03/distance-metrics-euclidean-manhattan-minkowski-oh.html

In [206]:
highest_idx = np.argmax(data_norm[:,-1]) 
highest_spender = data_norm[highest_idx]
highest_spender

array([-0.27630176, -1.58632148,  1.89449216])

In [207]:
distances = np.linalg.norm(data_norm - highest_spender, axis=1)
distances.shape

(200,)

In [208]:
distances

array([2.60142971, 1.23333086, 3.76921616, 1.21828611, 2.30965307,
       1.29364526, 3.61060691, 0.88362925, 4.2686173 , 1.10790218,
       4.02031893, 0.        , 3.65516654, 1.16366029, 3.34195613,
       1.21438449, 2.48575237, 1.67509024, 2.98272515, 0.15753602,
       2.49189884, 1.25310701, 3.7406563 , 1.07408784, 3.58695137,
       0.85964041, 2.72001617, 1.51468853, 2.69134635, 1.05089524,
       4.12274443, 1.48478417, 3.94410976, 1.35936908, 3.49054992,
       1.33542052, 3.2732259 , 1.21464971, 2.91694978, 1.58081869,
       3.36667373, 1.10589185, 2.72670557, 1.68565757, 3.03143718,
       1.71702965, 2.17235359, 2.24663296, 2.3925977 , 2.37097334,
       2.26039964, 1.7560252 , 1.99336143, 2.46944546, 2.52839349,
       2.57890935, 2.4181941 , 3.33136264, 2.20547114, 2.63899874,
       3.18716923, 2.30181951, 3.12177776, 2.3265663 , 2.95560585,
       2.26387309, 2.27452553, 3.27934571, 2.22601803, 2.31232494,
       3.24627439, 2.63618905, 2.89601555, 2.72135538, 2.97096075,
       2.29211716, 2.34282034, 2.41525835, 2.4198324 , 2.7732311 ,
       2.78386786, 2.17918219, 3.48262944, 2.63949483, 2.33511179,
       2.62461777, 2.58793592, 2.42733816, 2.12448187, 2.75831253,
       3.29509771, 2.98151989, 2.66219255, 2.79715599, 2.71882768,
       2.53011405, 2.69554426, 2.52928188, 2.88738989, 2.73799524,
       2.91640428, 2.76103424, 3.2216872 , 2.45535678, 2.54754012,
       2.93256196, 3.37472048, 2.98552608, 3.62708221, 3.41908775,
       3.284082  , 2.6816023 , 2.80948383, 2.91585879, 2.9139829 ,
       2.8319443 , 3.44195856, 2.55023197, 3.0661923 , 2.67845314,
       2.54420757, 2.94097371, 2.51087289, 1.95477004, 3.45194629,
       2.14505502, 3.23144526, 2.02295508, 4.3101303 , 2.20316217,
       4.1095934 , 2.21132918, 3.31286095, 2.31439656, 4.3271289 ,
       2.14851417, 4.17393487, 2.30510278, 4.20279698, 2.34644932,
       4.51425877, 2.16089456, 3.19876854, 2.23536661, 4.10163601,
       2.27143796, 3.42829267, 2.4267941 , 3.74330259, 2.28006888,
       3.94143989, 2.31003366, 3.85934843, 2.43209881, 4.02438303,
       2.35623176, 4.42339327, 2.42175266, 4.42164638, 2.49380385,
       3.69991192, 2.4116585 , 4.4984127 , 2.3952051 , 3.94164189,
       2.68691784, 4.02471319, 2.56607943, 3.81506978, 2.95572386,
       4.24406688, 2.80306976, 4.32200501, 2.61069516, 4.42395983,
       2.70551102, 4.50500963, 2.93638515, 4.67264088, 2.84606566,
       3.95598871, 3.02735335, 4.51109132, 3.07576386, 3.86461116,
       3.07554613, 4.48698791, 3.39071378, 4.53863108, 3.25276324,
       4.35777035, 3.41799361, 5.03728347, 3.60777283, 5.09765265,
       3.93252293, 4.97920821, 4.20338068, 5.49731535, 4.56076005])

In [209]:
similar_customers_idx = distances <= 1.0
similar_customers = data_new[similar_customers_idx]
similar_customers

array([[ 8,  0, 23, 18, 94],
       [12,  0, 35, 19, 99],
       [20,  0, 35, 23, 98],
       [26,  1, 29, 28, 82]])

Younger female customer has similar high spending score.

The following are code from ChatGPT

- https://chatgpt.com/share/67988b3a-8488-8000-bed0-af7edf4d92e2

import numpy as np
import pandas as pd

# Sample dataset (replace with your actual dataset)
data = {
    'CustomerID': [1, 2, 3, 4, 5],
    'Age': [20, 34, 28, 40, 22],
    'Annual Income (k$)': [15, 18, 25, 35, 20],
    'Spending Score': [39, 81, 77, 40, 90],
}

# Convert the dataset into a DataFrame
df = pd.DataFrame(data)

print(df)
# Step 1: Normalize the dataset (excluding CustomerID)
features = df.drop(columns=['CustomerID'])
normalized_data = (features - features.mean()) / features.std()

# Step 2: Identify the customer with the highest Spending Score
highest_spender_index = normalized_data['Spending Score'].idxmax()

# Step 3: Compute Euclidean distances
highest_spender_vector = normalized_data.loc[highest_spender_index].values
distances = np.linalg.norm(normalized_data.values - highest_spender_vector, axis=1)

# Step 4: Add distances to the DataFrame
df['Distance to Highest Spender'] = distances

# Step 5: Identify similar customers (set a threshold for similarity)
threshold = 1.0  # Adjust based on your needs
similar_customers = df[df['Distance to Highest Spender'] <= threshold]

print("Normalized Data:")
print(normalized_data)
print("\nCustomers Similar to the Highest Spender:")
print(similar_customers)

### EDA Findings

1. There are more female high spender compare to male spender. 
2. Average income is around 60K which is not high. This indicate that high spender is not necessary with high income and is about. Average age for both male and female customer is about 40 years old. This is also inline with the total average.  
3. The average income of the top 10 customer is only 58K. Average age is only 31 years old. The top spender is a 35 year old female with income of only 19K. The number of male and female customer is even.
4. The top spenders average income is inline with total average income. The average age of the top customer is lower then the total average, 
5. There is little or no correlation between income and spending score. Although there is a negative correlation between age and spending. This indicate that the younger adults are the high spender.
6. Average income of young adults is 44K with average spending score of 55.77. Adults older than 25 has average income of 64K with spending score of 49. This shows that young adults has high spending score although the income is lower.  
7. The high spending group belongs to the younger working adults specially the group 40 years old and below. Their income is slightly above average.
8. Young adult female customers has similar score with the top spender.


Based on the findings above, the mall management should concentrate on younger working adults between 25 to 40 years old.